# Generated by Django 5.2.1 on 2025-05-15 12:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0003_alter_user_managers_user_full_name_alter_user_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_phone_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='devicesession',
            name='device_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='devicesession',
            name='expires_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='devicesession',
            name='refresh_token',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='devicesession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_sessions', to=settings.AUTH_USER_MODEL),
        ),
    ]
