# Generated by Django 5.2.1 on 2025-05-15 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0004_user_is_phone_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicesession',
            name='device_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='devicesession',
            name='device_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
